Improve the readme
Ashwatthaamaa/Neuwaita pull request #4
Opened 2022-05-21 15:36 UTC by axtloss

2022-05-21 15:43 UTC, TheEvilSkeleton requested changes

2022-05-21 15:43 UTC, TheEvilSkeleton commented on README.md
> +## Requesting new icons :
```suggestion
## Requesting new icons:
```

2022-05-21 15:43 UTC, TheEvilSkeleton commented on README.md
> +### How to find the **Actual name** of the icon ?
```suggestion
### How to find the **Actual name** of the icon?
```

2022-05-21 15:43 UTC, TheEvilSkeleton commented on README.md
> +I understand you really want the icon but while making an icon request please mention the [actual name of the icon](https://github.com/Ashwatthaamaa/Neuwaita#how-to-find-the-actual-name-of-the-icon-)
```suggestion
I understand you really want the icon but while making an icon request please mention the [actual name of the icon](#how-to-find-the-actual-name-of-the-icon) file that you want to request.
```

2022-05-21 15:43 UTC, TheEvilSkeleton commented on README.md
> +I understand you really want the icon but when making an icon request please include the [actual name of the icon](https://github.com/Ashwatthaamaa/Neuwaita#how-to-find-the-actual-name-of-the-icon-)
```suggestion
I understand you really want the icon but when making an icon request please include the [actual name of the icon](#how-to-find-the-actual-name-of-the-icon) that you want to request.
```

2022-05-21 16:18 UTC, meisme-dev requested changes
"A neumorphic take on adwaita theme" should be "A neumorphic take on the Adwaita theme"

2022-05-21 16:27 UTC, axtloss commented
Should be ready to merge now.

2022-05-22 02:15 UTC, merged

2022-05-22 05:20 UTC, TheEvilSkeleton commented
@Ashwatthaamaa a little tip, you might want to squash commits before merging. This prevents the commit history from cluttering:
![image](https://user-images.githubusercontent.com/50847364/169680050-1efc9e4b-dcf2-4597-a119-ee83669b08b3.png)